stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:${CICD_GIT_COMMIT}
- name: dbops
  steps:
  - runScriptConfig:
      name: 'create master db'
      image: mysql:5.7
      shellScript: |-
        export MYSQL_PIPELINE=$(echo "${CICD_PIPELINE_ID}" | tr -d '-')
        mysql --host=${MYSQL_HOST} --user=${MYSQL_USER} --password=${MYSQL_PWD} -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_PIPELINE}_master"
    envFrom:
    - sourceName: rds-mysql-root
      sourceKey: host
      targetKey: MYSQL_HOST
    - sourceName: rds-mysql-root
      sourceKey: port
      targetKey: MYSQL_TCP_PORT
    - sourceName: rds-mysql-root
      sourceKey: pass
      targetKey: MYSQL_PWD
    - sourceName: rds-mysql-root
      sourceKey: user
      targetKey: MYSQL_USER
  - runScriptConfig:
      name: 'Deply from master db'
      image: mysql:5.7
      shellScript: |-
        export MYSQL_PIPELINE=$(echo "${CICD_PIPELINE_ID}" | tr -d '-')
        mysqldump --host=${MYSQL_HOST} --user=${MYSQL_USER} --password=${MYSQL_PWD} --no-create-db ${MYSQL_PIPELINE}_master > /tmp/export.sql
        mysql --host=${MYSQL_HOST} --user=${MYSQL_USER} --password=${MYSQL_PWD} -e "DROP DATABASE IF EXISTS ${MYSQL_PIPELINE}_${CICD_GIT_BRANCH}"
        mysql --host=${MYSQL_HOST} --user=${MYSQL_USER} --password=${MYSQL_PWD} -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_PIPELINE}_${CICD_GIT_BRANCH}"
        mysql --host=${MYSQL_HOST} --user=${MYSQL_USER} --password=${MYSQL_PWD} ${MYSQL_PIPELINE}_${CICD_GIT_BRANCH} < /tmp/export.sql
    envFrom:
    - sourceName: rds-mysql-root
      sourceKey: host
      targetKey: MYSQL_HOST
    - sourceName: rds-mysql-root
      sourceKey: port
      targetKey: MYSQL_TCP_PORT
    - sourceName: rds-mysql-root
      sourceKey: pass
      targetKey: MYSQL_PWD
    - sourceName: rds-mysql-root
      sourceKey: user
      targetKey: MYSQL_USER
    when:
      branch:
        exclude:
        - master
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:devpanel-catalog-php-fpm
      version: 1.0.3
      answers:
        app.isdev: "true"
        database.enabled: "true"
        test: ${MYSQL_HOST}
        image.registry: ${CICD_LOCAL_REGISTRY}
        image.repository: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}
        image.tag: ${CICD_GIT_COMMIT}
        port: "3306"
      name: ${CICD_PIPELINE_ID}-${CICD_GIT_BRANCH}
      targetNamespace: ${CICD_PIPELINE_ID}-${CICD_GIT_BRANCH}
    envFrom:
    - sourceName: rds-mysql-root
      sourceKey: host
      targetKey: MYSQL_HOST
    - sourceName: rds-mysql-root
      sourceKey: port
      targetKey: MYSQL_TCP_PORT
    - sourceName: rds-mysql-root
      sourceKey: pass
      targetKey: MYSQL_PWD
    - sourceName: rds-mysql-root
      sourceKey: user
      targetKey: MYSQL_USER
timeout: 60
notification: {}
