stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:devpanel-catalog-php-fpm
      version: 1.0.2
      answers:
        image.registry: docker-registry.p-56lsx-pipeline
        image.repository: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}
        image.tag: latest
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
      targetNamespace: default
timeout: 60
notification: {}
