stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:${CICD_GIT_COMMIT}
- name: deploy
  steps:
  - runScriptConfig:
      image: mysql:5.7
      shellScript: mysql --host=${DB_HOST} --password=${DB_PASS} --user="${DB_USER}"
        --port=3306 -e "CREATE DATABASE IF NOT EXISTS ${CICD_PIPELINE_ID}_${CICD_GIT_BRANCH}"
    envFrom:
    - sourceName: ns-qzchs
      sourceKey: host
      targetKey: DB_HOST
    - sourceName: ns-qzchs
      sourceKey: port
      targetKey: DB_PORT
    - sourceName: ns-qzchs
      sourceKey: pass
      targetKey: DB_PASS
    - sourceName: ns-qzchs
      sourceKey: user
      targetKey: DB_USER
  - applyAppConfig:
      catalogTemplate: cattle-global-data:devpanel-catalog-php-fpm
      version: 1.0.3
      answers:
        app.isdev: "true"
        database.enabled: "false"
        image.registry: 127.0.0.1:34305
        image.repository: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}
        image.tag: ${CICD_GIT_COMMIT}
        port: "3306"
      name: ${CICD_PIPELINE_ID}-${CICD_GIT_BRANCH}
      targetNamespace: ${CICD_PIPELINE_ID}-${CICD_GIT_BRANCH}
timeout: 60
notification: {}
