stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:${CICD_GIT_COMMIT}
- name: deploy
  steps:
  - runScriptConfig:
      image: mysql:5.7
      shellScript: mysql -u${MYSQL_USER} -e "CREATE DATABASE IF NOT EXISTS master"
#        mysqldump -h ${MYSQL_HOST} -u ${MYSQL_USER} -p ${MYSQL_PWD} -P ${MYSQL_TCP_PORT} --no-create-db master > /tmp/export.sql
#        mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -p ${MYSQL_PWD} -P ${MYSQL_TCP_PORT} -e "CREATE DATABASE IF NOT EXISTS ${CICD_GIT_BRANCH}"
#        mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -p ${MYSQL_PWD} -P ${MYSQL_TCP_PORT} ${CICD_GIT_BRANCH} < /tmp/export.sql
    envFrom:
    - sourceName: ns-qzchs
      sourceKey: host
      targetKey: MYSQL_HOST
    - sourceName: ns-qzchs
      sourceKey: port
      targetKey: MYSQL_TCP_PORT
    - sourceName: ns-qzchs
      sourceKey: pass
      targetKey: MYSQL_PWD
    - sourceName: ns-qzchs
      sourceKey: user
      targetKey: MYSQL_USER
  - applyAppConfig:
      catalogTemplate: cattle-global-data:devpanel-catalog-php-fpm
      version: 1.0.3
      answers:
        app.isdev: "true"
        database.enabled: "false"
        image.registry: 127.0.0.1:34305
        image.repository: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}
        image.tag: ${CICD_GIT_COMMIT}
        port: "3306"
      name: ${CICD_PIPELINE_ID}-${CICD_GIT_BRANCH}
      targetNamespace: ${CICD_PIPELINE_ID}-${CICD_GIT_BRANCH}
timeout: 60
notification: {}
