stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:${CICD_GIT_COMMIT}
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:devpanel-catalog-php-fpm
      version: 1.0.2
      answers:
        image.registry: 127.0.0.1:34305
        image.repository: ${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}
        image.tag: ${CICD_GIT_COMMIT}
        app.isdev: true
        database.database: ${CICD_PIPELINE_ID}-${CICD_GIT_BRANCH}
      name: ${CICD_PIPELINE_ID}-${CICD_GIT_BRANCH}
      targetNamespace: ${CICD_PIPELINE_ID}-${CICD_GIT_BRANCH}
timeout: 60
notification: {}
